#!/usr/bin/env python3
"""
t-SNE visualization of behavioral fingerprints.

Loads fingerprints.csv from the two dedicated fingerprint-export runs
(dedup and dedup+div), pools them, runs t-SNE once on the combined set,
then plots by condition with distinct colors.

Each row in fingerprints.csv is a fingerprint vector (no header,
comma-separated integers).  The file is generated by setting
EXPORT_FINGERPRINTS=1 during a FunSearch run.

Output:
  docs/figures/tsne_fingerprints.pdf  (and .png)

Usage (from efficient-funsearch/):
  python scripts/plot_tsne_fingerprints.py
"""

import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from sklearn.manifold import TSNE

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
LOG_BASE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "funsearch-baseline", "logs"
)
OUT_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "docs", "figures"
)
os.makedirs(OUT_DIR, exist_ok=True)

# Directories that contain fingerprints.csv
FP_DIRS = {
    "Dedup":      "layer1_dedup_150_fp",
    "Dedup + Div": "layer2_dedup_div_150_fp",
}
COLORS = {
    "Dedup":       "#2196F3",
    "Dedup + Div": "#FF9800",
}
MARKERS = {
    "Dedup":       "o",
    "Dedup + Div": "^",
}

TSNE_PERPLEXITY = 20   # lower than default 30 because sample sizes are small (~100)
TSNE_SEED = 42


def _load_fingerprints(fp_dir: str) -> np.ndarray:
    """Load fingerprints.csv; return float32 array of shape (n, dim).

    The CSV format is produced by evaluator.py:
      sample_num, v1, v2, ..., vD
    so we drop the first column (sample index) — it is metadata,
    not part of the behavioral fingerprint.
    """
    path = os.path.join(LOG_BASE, fp_dir, "fingerprints.csv")
    rows = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split(",")
            try:
                rows.append([float(x) for x in parts[1:]])  # drop sample_num
            except ValueError:
                continue  # skip header-like lines if any
    return np.array(rows, dtype=np.float32)


def main():
    # Load and label fingerprints
    all_fps = []
    all_labels = []
    for label, fp_dir in FP_DIRS.items():
        fps = _load_fingerprints(fp_dir)
        print(f"  {label}: {fps.shape[0]} fingerprints, dim={fps.shape[1]}")
        all_fps.append(fps)
        all_labels.extend([label] * len(fps))

    X = np.vstack(all_fps)         # (n_total, dim)
    labels = np.array(all_labels)  # (n_total,)

    print(f"Total fingerprints: {len(X)}, dim={X.shape[1]}")
    print("Running t-SNE...")
    tsne = TSNE(
        n_components=2,
        perplexity=TSNE_PERPLEXITY,
        random_state=TSNE_SEED,
        max_iter=1000,
        init="random",
    )
    X_2d = tsne.fit_transform(X)

    # Plot
    fig, ax = plt.subplots(figsize=(6, 5))
    for label in FP_DIRS:
        mask = labels == label
        ax.scatter(
            X_2d[mask, 0], X_2d[mask, 1],
            c=COLORS[label],
            marker=MARKERS[label],
            s=30,
            alpha=0.7,
            label=f"{label} (n={mask.sum()})",
            linewidths=0,
        )

    ax.set_xlabel("t-SNE Dim 1", fontsize=11)
    ax.set_ylabel("t-SNE Dim 2", fontsize=11)
    ax.set_title("Behavioral Fingerprints — t-SNE (perplexity=20)", fontsize=12)
    ax.legend(fontsize=10)
    ax.grid(linestyle="--", alpha=0.3)
    plt.tight_layout()

    out_pdf = os.path.join(OUT_DIR, "tsne_fingerprints.pdf")
    out_png = os.path.join(OUT_DIR, "tsne_fingerprints.png")
    fig.savefig(out_pdf, bbox_inches="tight")
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    print(f"Saved: {out_pdf}")
    print(f"Saved: {out_png}")


if __name__ == "__main__":
    main()
