"""
Data models for the metrics module.
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass
class EfficiencyMetrics:
    """
    Metrics for tracking the efficiency improvements of enhanced FunSearch.

    Records statistics about duplicate detection and resource savings.
    """

    session_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    """Unique identifier for this experimental session."""

    total_programs_generated: int = 0
    """Total number of programs generated by LLM."""

    duplicates_detected: int = 0
    """Number of duplicates identified by the detector."""

    duplicates_filtered: int = 0
    """Number of duplicates that were actually filtered out."""

    programs_evaluated: int = 0
    """Number of programs that were actually evaluated."""

    llm_queries_saved: int = 0
    """Estimated number of LLM queries saved."""

    evaluation_time_saved: float = 0.0
    """Estimated evaluation time saved in seconds."""

    detection_time_total: float = 0.0
    """Total time spent on duplicate detection in seconds."""

    created_at: datetime = field(default_factory=datetime.now)
    """When this metrics session started."""

    metadata: dict[str, Any] = field(default_factory=dict)
    """Additional metadata."""

    @property
    def sample_efficiency(self) -> float:
        """Sample efficiency η = N_unique / N_total."""
        if self.total_programs_generated == 0:
            return 0.0
        return self.programs_evaluated / self.total_programs_generated

    @property
    def duplicate_detection_rate(self) -> float:
        """
        Proportion of generated programs that were duplicates.

        Returns 0.0 if no programs were generated.
        """
        if self.total_programs_generated == 0:
            return 0.0
        return self.duplicates_detected / self.total_programs_generated

    @property
    def llm_savings_rate(self) -> float:
        """
        Proportion of LLM queries saved.

        Returns 0.0 if no programs were generated.
        """
        if self.total_programs_generated == 0:
            return 0.0
        return self.llm_queries_saved / self.total_programs_generated

    @property
    def time_savings_ratio(self) -> float:
        """
        Ratio of time saved to total time (including detection).

        Returns 0.0 if no time was spent.
        """
        total_time = self.evaluation_time_saved + self.detection_time_total
        if total_time == 0:
            return 0.0
        return self.evaluation_time_saved / total_time

    @property
    def net_time_saved(self) -> float:
        """
        Net time saved (evaluation time saved minus detection time).

        Can be negative if detection took longer than saved evaluation time.
        """
        return self.evaluation_time_saved - self.detection_time_total

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "session_id": self.session_id,
            "total_programs_generated": self.total_programs_generated,
            "duplicates_detected": self.duplicates_detected,
            "duplicates_filtered": self.duplicates_filtered,
            "programs_evaluated": self.programs_evaluated,
            "llm_queries_saved": self.llm_queries_saved,
            "evaluation_time_saved": self.evaluation_time_saved,
            "detection_time_total": self.detection_time_total,
            "sample_efficiency": self.sample_efficiency,
            "duplicate_detection_rate": self.duplicate_detection_rate,
            "llm_savings_rate": self.llm_savings_rate,
            "time_savings_ratio": self.time_savings_ratio,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "EfficiencyMetrics":
        """Create from dictionary."""
        created_at = data.get("created_at")
        if isinstance(created_at, str):
            created_at = datetime.fromisoformat(created_at)
        elif created_at is None:
            created_at = datetime.now()

        return cls(
            session_id=data.get("session_id", str(uuid.uuid4())[:8]),
            total_programs_generated=data.get("total_programs_generated", 0),
            duplicates_detected=data.get("duplicates_detected", 0),
            duplicates_filtered=data.get("duplicates_filtered", 0),
            programs_evaluated=data.get("programs_evaluated", 0),
            llm_queries_saved=data.get("llm_queries_saved", 0),
            evaluation_time_saved=data.get("evaluation_time_saved", 0.0),
            detection_time_total=data.get("detection_time_total", 0.0),
            created_at=created_at,
            metadata=data.get("metadata", {}),
        )

    def summary(self) -> str:
        """Return a human-readable summary."""
        return f"""
Efficiency Metrics (Session: {self.session_id})
========================================
Programs Generated:    {self.total_programs_generated}
Duplicates Detected:   {self.duplicates_detected} ({self.duplicate_detection_rate:.1%})
Programs Evaluated:    {self.programs_evaluated}

LLM Queries Saved:     {self.llm_queries_saved} ({self.llm_savings_rate:.1%})
Time Saved:            {self.evaluation_time_saved:.2f}s
Detection Time:        {self.detection_time_total:.2f}s
Net Time Saved:        {self.net_time_saved:.2f}s
"""
