import http.client
import json
import multiprocessing
import os
import sys
from collections.abc import Collection
from typing import Any

import bin_packing_utils
from implementation import (
    code_manipulation,
    config,
    evaluator,
    evaluator_accelerate,
    funsearch,
    sampler,
)

# Phase 2: Add repo root to sys.path so we can import src.dedup
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))


def _build_per_instance_inputs(dataset: dict[str, dict[str, Any]]) -> dict[str, dict[str, dict[str, Any]]]:
    """Wrap each bin-packing instance as its own top-level test input.

    FunSearch records one score per top-level input key. Splitting OR3 into
    per-instance inputs makes cluster signatures reflect the full score pattern
    across instances instead of collapsing to a single averaged scalar.
    """
    return {
        instance_name: {instance_name: instance}
        for instance_name, instance in dataset.items()
    }


def _trim_preface_of_body(sample: str) -> str:
    """Trim the redundant descriptions/symbols/'def' declaration before the function body.
    Please see my comments in sampler.LLM (in sampler.py).
    Since the LLM used in this file is not a pure code completion LLM, this trim function is required.

    -Example sample (function & description generated by LLM):
    -------------------------------------
    This is the optimized function ...
    def priority_v2(...) -> ...:
        return ...
    This function aims to ...
    -------------------------------------
    -This function removes the description above the function's signature, and the function's signature.
    -The indent of the code is preserved.
    -Return of this function:
    -------------------------------------
        return ...
    This function aims to ...
    -------------------------------------
    """
    lines = sample.splitlines()
    func_body_lineno = 0
    find_def_declaration = False
    for lineno, line in enumerate(lines):
        # find the first 'def' statement in the given code
        if line[:3] == 'def':
            func_body_lineno = lineno
            find_def_declaration = True
            break
    if find_def_declaration:
        code = ''
        for line in lines[func_body_lineno + 1:]:
            code += line + '\n'
        return code
    return sample


class LLMAPI(sampler.LLM):
    """Language model that predicts continuation of provided source code.
    """

    def __init__(self, samples_per_prompt: int, trim=True):
        super().__init__(samples_per_prompt)
        additional_prompt = ('Complete a different and more complex Python function. '
                             'Be creative and you can insert multiple if-else and for-loop in the code logic.'
                             'Only output the Python code, no descriptions.')
        self._additional_prompt = additional_prompt
        self._trim = trim

    def draw_samples(self, prompt: str) -> Collection[str]:
        """Returns multiple predicted continuations of `prompt`."""
        return [self._draw_sample(prompt) for _ in range(self._samples_per_prompt)]

    def _draw_sample(self, content: str) -> str:
        prompt = '\n'.join([content, self._additional_prompt])
        while True:
            try:
                # Read API config from environment variables for easy provider switching
                api_base = os.environ.get('API_BASE', 'api.bltcy.ai')
                api_key = os.environ['API_KEY']  # Must be set, otherwise raise error
                api_model = os.environ.get('API_MODEL', 'gpt-5-nano')

                conn = http.client.HTTPSConnection(api_base)
                payload = json.dumps({
                    "max_tokens": 4096,  # Reasoning models need many tokens to "think" first; 512 is insufficient
                    "model": api_model,
                    "messages": [
                        {
                            "role": "user",
                            "content": prompt
                        }
                    ]
                })
                headers = {
                    'Authorization': f'Bearer {api_key}',
                    'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
                    'Content-Type': 'application/json'
                }
                conn.request("POST", "/v1/chat/completions", payload, headers)
                res = conn.getresponse()
                data = res.read().decode("utf-8")
                data = json.loads(data)
                if 'choices' not in data:
                    print(f"[LLMAPI] Unexpected response: {data}")
                    continue
                response = data['choices'][0]['message']['content']

                # Save raw LLM output before trimming, for debugging trim issues
                raw_dir = os.path.join('logs', 'raw_llm_outputs')
                os.makedirs(raw_dir, exist_ok=True)
                raw_count = len(os.listdir(raw_dir))
                with open(os.path.join(raw_dir, f'raw_{raw_count:04d}.txt'), 'w') as f:
                    f.write(response)

                # trim function
                if self._trim:
                    response = _trim_preface_of_body(response)
                return response
            except Exception as e:
                print(f"[LLMAPI] Error in _draw_sample: {e}")
                continue


class Sandbox(evaluator.Sandbox):
    """Sandbox for executing generated code. Implemented by RZ.

    RZ: Sandbox returns the 'score' of the program and:
    1) avoids the generated code to be harmful (accessing the internet, take up too much RAM).
    2) stops the execution of the code in time (avoid endless loop).
    """

    def __init__(self, verbose=False, numba_accelerate=False):  # numba not installed, disable acceleration
        """
        Args:
            verbose         : Print evaluate information.
            numba_accelerate: Use numba to accelerate the evaluation. It should be noted that not all numpy functions
                              support numba acceleration, such as np.piecewise().
        """
        self._verbose = verbose
        self._numba_accelerate = numba_accelerate

    def run(
            self,
            program: str,
            function_to_run: str,  # RZ: refers to the name of the function to run (e.g., 'evaluate')
            function_to_evolve: str,  # RZ: accelerate the code by decorating @numba.jit() on function_to_evolve.
            inputs: Any,  # refers to the dataset
            test_input: str,  # refers to the current instance
            timeout_seconds: int,
            **kwargs  # RZ: add this
    ) -> tuple[Any, bool]:
        """Returns `function_to_run(test_input)` and whether execution succeeded.

        RZ: If the generated code (generated by LLM) is executed successfully,
        the output of this function is the score of a given program.
        RZ: PLEASE NOTE THAT this SandBox is only designed for bin-packing problem.
        """
        dataset = inputs[test_input]
        result_queue = multiprocessing.Queue()
        process = multiprocessing.Process(
            target=self._compile_and_run_function,
            args=(program, function_to_run, function_to_evolve, dataset, self._numba_accelerate, result_queue)
        )
        process.start()
        process.join(timeout=timeout_seconds)
        if process.is_alive():
            # if the process is not finished in time, we consider the program illegal
            process.terminate()
            process.join()
            results = None, False
        else:
            if not result_queue.empty():
                results = result_queue.get_nowait()
            else:
                results = None, False

        if self._verbose:
            print('================= Evaluated Program =================')
            program_: code_manipulation.Program = code_manipulation.text_to_program(text=program)
            func_to_evolve_: str = kwargs.get('func_to_evolve', 'priority')
            function_: code_manipulation.Function = program_.get_function(func_to_evolve_)
            function_: str = str(function_).strip('\n')
            print(f'{function_}')
            print('-----------------------------------------------------')
            print(f'Score: {str(results)}')
            print('=====================================================')
            print('\n\n')

        return results

    def _compile_and_run_function(self, program, function_to_run, function_to_evolve, dataset, numba_accelerate,
                                  result_queue):
        try:
            # optimize the code (decorate function_to_run with @numba.jit())
            if numba_accelerate:
                program = evaluator_accelerate.add_numba_decorator(
                    program=program,
                    function_to_evolve=function_to_evolve
                )
            # compile the program, and maps the global func/var/class name to its address
            all_globals_namespace = {}
            # execute the program, map func/var/class to global namespace
            exec(program, all_globals_namespace)
            # get the pointer of 'function_to_run'
            function_to_run = all_globals_namespace[function_to_run]
            # return the execution results
            results = function_to_run(dataset)
            # the results must be int or float
            if not isinstance(results, (int, float)):
                result_queue.put((None, False))
                return
            result_queue.put((results, True))
        except:
            # if raise any exception, we assume the execution failed
            result_queue.put((None, False))


specification = r'''
import numpy as np


def get_valid_bin_indices(item: float, bins: np.ndarray) -> np.ndarray:
    """Returns indices of bins in which item can fit."""
    return np.nonzero((bins - item) >= 0)[0]


def online_binpack(
        items: tuple[float, ...], bins: np.ndarray
) -> tuple[list[list[float, ...], ...], np.ndarray]:
    """Performs online binpacking of `items` into `bins`."""
    # Track which items are added to each bin.
    packing = [[] for _ in bins]
    # Add items to bins.
    for item in items:
        # Extract bins that have sufficient space to fit item.
        valid_bin_indices = get_valid_bin_indices(item, bins)
        # Score each bin based on heuristic.
        priorities = priority(item, bins[valid_bin_indices])
        # Add item to bin with highest priority.
        best_bin = valid_bin_indices[np.argmax(priorities)]
        bins[best_bin] -= item
        packing[best_bin].append(item)
    # Remove unused bins from packing.
    packing = [bin_items for bin_items in packing if bin_items]
    return packing, bins


@funsearch.run
def evaluate(instances: dict) -> float:
    """Evaluate heuristic function on a set of online binpacking instances."""
    # List storing number of bins used for each instance.
    num_bins = []
    # Perform online binpacking for each instance.
    for name in instances:
        instance = instances[name]
        capacity = instance['capacity']
        items = instance['items']
        # Create num_items bins so there will always be space for all items,
        # regardless of packing order. Array has shape (num_items,).
        bins = np.array([capacity for _ in range(instance['num_items'])])
        # Pack items into bins and return remaining capacity in bins_packed, which
        # has shape (num_items,).
        _, bins_packed = online_binpack(items, bins)
        # If remaining capacity in a bin is equal to initial capacity, then it is
        # unused. Count number of used bins.
        num_bins.append((bins_packed != capacity).sum())
    # Score of heuristic function is negative of average number of bins used
    # across instances (as we want to minimize number of bins).
    return -np.mean(num_bins)


@funsearch.evolve
def priority(item: float, bins: np.ndarray) -> np.ndarray:
    """Returns priority with which we want to add item to each bin.

    Args:
        item: Size of item to be added to the bin.
        bins: Array of capacities for each bin.

    Return:
        Array of same size as bins with priority score of each bin.
    """
    ratios = item / bins
    log_ratios = np.log(ratios)
    priorities = -log_ratios
    return priorities
'''

# It should be noted that the if __name__ == '__main__' is required.
# Because the inner code uses multiprocess evaluation.
if __name__ == '__main__':
    # Phase 2: Import dedup config (can be disabled via env var DEDUP_ENABLED=0)
    DEDUP_ENABLED = os.environ.get('DEDUP_ENABLED', '1') != '0'
    dedup_config = None
    if DEDUP_ENABLED:
        try:
            from src.dedup.dedup_config import DedupConfig
            dedup_config = DedupConfig(enabled=True)
        except ImportError:
            print("[Warning] src.dedup not found, disabling dedup")
            DEDUP_ENABLED = False

    # Phase 3: Diversity-guided selection (optional)
    DIVERSITY_ENABLED = os.environ.get('DIVERSITY_ENABLED', '0') == '1'
    diversity_config = None
    if DIVERSITY_ENABLED:
        try:
            from implementation.config import DiversityConfig
            diversity_config = DiversityConfig(
                enabled=True,
                beta_init=float(os.environ.get('DIVERSITY_BETA_INIT', '0.3')),
                beta_decay_period=int(os.environ.get('DIVERSITY_BETA_DECAY', '350')),
            )
            print(f"[Config] Diversity-guided selection enabled: {diversity_config}")
        except Exception as e:
            print(f"[Config] Failed to create DiversityConfig, disabling diversity: {e}")
            DIVERSITY_ENABLED = False

    class_config = config.ClassConfig(llm_class=LLMAPI, sandbox_class=Sandbox)
    config = config.Config(
        samples_per_prompt=4,
        evaluate_timeout_seconds=30,
        dedup=dedup_config,  # Phase 2: Pass dedup config
        diversity=diversity_config,
    )

    bin_packing_or3 = _build_per_instance_inputs(bin_packing_utils.datasets['OR3'])
    # --- 15-sample small-scale validation (passed, Round 2 dedup rate 50%, best=-232.95) ---
    # global_max_sample_num = 16
    # funsearch.main(
    #     specification=specification,
    #     inputs=bin_packing_or3,
    #     config=config,
    #     max_sample_nums=global_max_sample_num,
    #     class_config=class_config,
    #     log_dir='logs/dedup_15samples_v2',
    # )

    log_dir = os.environ.get('LOG_DIR', None)
    if log_dir is None:
        if DIVERSITY_ENABLED:
            log_dir = 'logs/diversity_50samples'
        elif DEDUP_ENABLED:
            log_dir = 'logs/dedup_50samples_v2'
        else:
            log_dir = 'logs/baseline_50samples'

    global_max_sample_num = 51  # Counter starts from 1, so set 51 to actually generate 50 LLM samples
    funsearch.main(
        specification=specification,
        inputs=bin_packing_or3,
        config=config,
        max_sample_nums=global_max_sample_num,
        class_config=class_config,
        log_dir=log_dir,
    )
